### PR TITLE
Fixing minor bugs in Tile component

### PR DESCRIPTION
**Pull request by Monte9**
Everytime a new component is added/fixed I implement it myself to see if I can improve the API in any way/fix bugs. 

@binoy14 I have updated the Tile component to fix the issues that I faced while implementing it. Create this PR for you to review it before it's merged. 

- added missing `activeOpacity` for Tile component
- added `iconContainerStyle` and also center Icon by default
- updated README for two typo's in props

### CODE REVIEW

**Comment by binoy14** [comment]
@Monte9 Looks good to me 👍

**Comment by Monte9** [comment]
Great! Merging it now.

**Comment by binoy14** [comment]
@Monte9 When do you plan to do a release?

**Comment by Monte9** [comment]
I'll do one right now. Hang tight.

**Comment by Monte9** [comment]
Done. Also @binoy14 I need to talk to you about something. Can you keep an eye out for an email from me? Thanks.

**Pull request merged**
