### PR TITLE
Support for disabled buttons

### PR DESCRIPTION
**Pull request by tolu360**
Perhaps you can add built-in support for 'disabled` buttons. Great work so far, by the way!

### CODE REVIEW

**Comment by dabit3** [comment]
@tolu360 Thanks, this is a great starting point. What do you think about having a default disabled color such as a light shade of grey? Also, how about the possibility of disabling any onPress method if the button is disabled? If you want to update the pr with something like this go ahead, but if you would like me to add this to the next version I can also do so. 

Thanks again for putting this here :)

**Comment by tolu360** [comment]
Hi @dabit3, so I took your suggestion because it was just brilliant. Have updated the PR to include a default color for the disabled state for buttons, please feel free to alter my color choice (added it to the colors config to allow for easy updates). As per, preventing `onPress` from firing when button is disabled, we get that for free - out of the box, RN handles that quite well.

**Comment by dabit3** [comment]
@tolu360 Hey thanks so much! I Have not forgotten about you, just been busy and need to test this out. I'll hopefully have this merge by the end of the week. Thanks again :)

**Comment by MelanieCLopez** [comment]
ok thank you ;)

**Comment by tolu360** [comment]
That's fine @dabit3

**Comment by dabit3** [comment]
@tolu360 thank so much for this pr, it's a great addition!

**Pull request merged**
